import React, { useState } from 'react';
import { View , Text, StyleSheet} from 'react-native';
import {Node} from './../components/Node';
import {NodeRow} from './../components/NodeRow';
import ReactNativeZoomableView from '@dudigital/react-native-zoomable-view/src/ReactNativeZoomableView';


export default function PathFinderPage() {

  const [boo,setBoo] = useState(true);

  const response = mock2;

  const row = response.map((nodeRow,keyRow) =>
        <NodeRow key={keyRow} style={styles.row}>
          {nodeRow.map((node,key) => <Node key={key} isActive={node.isActive}/>)}
        </NodeRow>
  );
      
  return <View style={{flex: 1}}>
    <ReactNativeZoomableView
      maxZoom={1.2}
      minZoom={0.3}
      zoomStep={1}
      initialZoom={0.4}
      bindToBorders={false}
      movementSensibility={0.5}
    >
      {row}

    </ReactNativeZoomableView>
    </View>
}


const styles = StyleSheet.create({
  map: {
    alignItems: "center",
  },
  row: {
    flexDirection: "row",
  },
});


//labs de elétrica -> atendimento de saúde
const mock1 = [
  [
      {x:1, y:1, isActive:false},
      {x:1,    y:2,   isActive:false},
      {x:1,    y:3,   isActive:false},
      {x:1,    y:4,   isActive:false},
      {x:1,    y:5,   isActive:false},
      {x:1,    y:6,   isActive:false},
      {x:1,    y:7,   isActive:false},
      {x:1,    y:8,   isActive:false},
      {x:1,    y:9,   isActive:false},
      {x:1,    y:10,  isActive:false},
      {x:1,    y:11,  isActive:false},
      {x:1,    y:12,  isActive:false},
      {x:1,    y:13,  isActive:false},
      {x:1,    y:14,  isActive:false},
      {x:1,    y:15,  isActive:false},
      {x:1,    y:16,  isActive:false},
      {x:1,    y:17,  isActive:false},
      {x:1,    y:18,  isActive:false},
      {x:1,    y:19,  isActive:false},
      {x:1,    y:20,  isActive:false},
  ],
  [
      {x:2,    y:1,   isActive:false},
      {x:2,    y:2,   isActive:false},
      {x:2,    y:3,   isActive:false},
      {x:2,    y:4,   isActive:false},
      {x:2,    y:5,   isActive:false},
      {x:2,    y:6,   isActive:false},
      {x:2,    y:7,   isActive:false},
      {x:2,    y:8,   isActive:false},
      {x:2,    y:9,   isActive:false},
      {x:2,    y:10,  isActive:false},
      {x:2,    y:11,  isActive:false},
      {x:2,    y:12,  isActive:false},
      {x:2,    y:13,  isActive:false},
      {x:2,    y:14,  isActive:false},
      {x:2,    y:15,  isActive:false},
      {x:2,    y:16,  isActive:false},
      {x:2,    y:17,  isActive:false},
      {x:2,    y:18,  isActive:false},
      {x:2,    y:19,  isActive:false},
      {x:2,    y:20,  isActive:false},
  ],
  [
      {x:3,    y:1,   isActive:false},
      {x:3,    y:2,   isActive:false},
      {x:3,    y:3,   isActive:false},
      {x:3,    y:4,   isActive:false},
      {x:3,    y:5,   isActive:false},
      {x:3,    y:6,   isActive:false},
      {x:3,    y:7,   isActive:false},
      {x:3,    y:8,   isActive:false},
      {x:3,    y:9,   isActive:false},
      {x:3,    y:10,  isActive:false},
      {x:3,    y:11,  isActive:false},
      {x:3,    y:12,  isActive:false},
      {x:3,    y:13,  isActive:false},
      {x:3,    y:14,  isActive:false},
      {x:3,    y:15,  isActive:false},
      {x:3,    y:16,  isActive:false},
      {x:3,    y:17,  isActive:false},
      {x:3,    y:18,  isActive:false},
      {x:3,    y:19,  isActive:false},
      {x:3,    y:20,  isActive:false},
  ],
  [
      {x:4,    y:1,   isActive:false},
      {x:4,    y:2,   isActive:false},
      {x:4,    y:3,   isActive:false},
      {x:4,    y:4,   isActive:false},
      {x:4,    y:5,   isActive:true},
      {x:4,    y:6,   isActive:true},
      {x:4,    y:7,   isActive:true},
      {x:4,    y:8,   isActive:true},
      {x:4,    y:9,   isActive:true},
      {x:4,    y:10,  isActive:true},
      {x:4,    y:11,  isActive:true},
      {x:4,    y:12,  isActive:true},
      {x:4,    y:13,  isActive:true},
      {x:4,    y:14,  isActive:true},
      {x:4,    y:15,  isActive:true},
      {x:4,    y:16,  isActive:true},
      {x:4,    y:17,  isActive:true},
      {x:4,    y:18,  isActive:false},
      {x:4,    y:19,  isActive:false},
      {x:4,    y:20,  isActive:false},
  ],
  [
      {x:5,    y:1,   isActive:false},
      {x:5,    y:2,   isActive:false},
      {x:5,    y:3,   isActive:false},
      {x:5,    y:4,   isActive:false},
      {x:5,    y:5,   isActive:false},
      {x:5,    y:6,   isActive:false},
      {x:5,    y:7,   isActive:false},
      {x:5,    y:8,   isActive:false},
      {x:5,    y:9,   isActive:false},
      {x:5,    y:10,  isActive:false},
      {x:5,    y:11,  isActive:false},
      {x:5,    y:12,  isActive:false},
      {x:5,    y:13,  isActive:false},
      {x:5,    y:14,  isActive:false},
      {x:5,    y:15,  isActive:false},
      {x:5,    y:16,  isActive:false},
      {x:5,    y:17,  isActive:true},
      {x:5,    y:18,  isActive:false},
      {x:5,    y:19,  isActive:false},
      {x:5,    y:20,  isActive:false},
  ],
  [
      {x:6,    y:1,   isActive:false},
      {x:6,    y:2,   isActive:false},
      {x:6,    y:3,   isActive:false},
      {x:6,    y:4,   isActive:false},
      {x:6,    y:5,   isActive:false},
      {x:6,    y:6,   isActive:false},
      {x:6,    y:7,   isActive:false},
      {x:6,    y:8,   isActive:false},
      {x:6,    y:9,   isActive:false},
      {x:6,    y:10,  isActive:false},
      {x:6,    y:11,  isActive:false},
      {x:6,    y:12,  isActive:false},
      {x:6,    y:13,  isActive:false},
      {x:6,    y:14,  isActive:false},
      {x:6,    y:15,  isActive:false},
      {x:6,    y:16,  isActive:false},
      {x:6,    y:17,  isActive:true},
      {x:6,    y:18,  isActive:false},
      {x:6,    y:19,  isActive:false},
      {x:6,    y:20,  isActive:false},
  ],
  [
      {x:7,    y:1,   isActive:false},
      {x:7,    y:2,   isActive:false},
      {x:7,    y:3,   isActive:false},
      {x:7,    y:4,   isActive:false},
      {x:7,    y:5,   isActive:false},
      {x:7,    y:6,   isActive:false},
      {x:7,    y:7,   isActive:false},
      {x:7,    y:8,   isActive:false},
      {x:7,    y:9,   isActive:false},
      {x:7,    y:10,  isActive:false},
      {x:7,    y:11,  isActive:false},
      {x:7,    y:12,  isActive:false},
      {x:7,    y:13,  isActive:false},
      {x:7,    y:14,  isActive:false},
      {x:7,    y:15,  isActive:false},
      {x:7,    y:16,  isActive:false},
      {x:7,    y:17,  isActive:true},
      {x:7,    y:18,  isActive:true},
      {x:7,    y:19,  isActive:true},
      {x:7,    y:20,  isActive:true},
  ],
  [
      {x:8,    y:1,   isActive:false},
      {x:8,    y:2,   isActive:false},
      {x:8,    y:3,   isActive:false},
      {x:8,    y:4,   isActive:false},
      {x:8,    y:5,   isActive:false},
      {x:8,    y:6,   isActive:false},
      {x:8,    y:7,   isActive:false},
      {x:8,    y:8,   isActive:false},
      {x:8,    y:9,   isActive:false},
      {x:8,    y:10,  isActive:false},
      {x:8,    y:11,  isActive:false},
      {x:8,    y:12,  isActive:false},
      {x:8,    y:13,  isActive:false},
      {x:8,    y:14,  isActive:false},
      {x:8,    y:15,  isActive:false},
      {x:8,    y:16,  isActive:false},
      {x:8,    y:17,  isActive:true},
      {x:8,    y:18,  isActive:false},
      {x:8,    y:19,  isActive:false},
      {x:8,    y:20,  isActive:false},
  ],
  [
      {x:9,    y:1,   isActive:false},
      {x:9,    y:2,   isActive:false},
      {x:9,    y:3,   isActive:false},
      {x:9,    y:4,   isActive:false},
      {x:9,    y:5,   isActive:false},
      {x:9,    y:6,   isActive:false},
      {x:9,    y:7,   isActive:false},
      {x:9,    y:8,   isActive:false},
      {x:9,    y:9,   isActive:false},
      {x:9,    y:10,  isActive:false},
      {x:9,    y:11,  isActive:false},
      {x:9,    y:12,  isActive:false},
      {x:9,    y:13,  isActive:false},
      {x:9,    y:14,  isActive:false},
      {x:9,    y:15,  isActive:false},
      {x:9,    y:16,  isActive:false},
      {x:9,    y:17,  isActive:true},
      {x:9,    y:18,  isActive:false},
      {x:9,    y:19,  isActive:false},
      {x:9,    y:20,  isActive:false},
  ],
  [
      {x:10,    y:1,   isActive:false},
      {x:10,    y:2,   isActive:false},
      {x:10,    y:3,   isActive:false},
      {x:10,    y:4,   isActive:false},
      {x:10,    y:5,   isActive:false},
      {x:10,    y:6,   isActive:false},
      {x:10,    y:7,   isActive:false},
      {x:10,    y:8,   isActive:false},
      {x:10,    y:9,   isActive:false},
      {x:10,    y:10,  isActive:false},
      {x:10,    y:11,  isActive:false},
      {x:10,    y:12,  isActive:false},
      {x:10,    y:13,  isActive:false},
      {x:10,    y:14,  isActive:false},
      {x:10,    y:15,  isActive:false},
      {x:10,    y:16,  isActive:false},
      {x:10,    y:17,  isActive:true},
      {x:10,    y:18,  isActive:false},
      {x:10,    y:19,  isActive:false},
      {x:10,    y:20,  isActive:false},
  ],
  [
      {x:11,    y:1,   isActive:false},
      {x:11,    y:2,   isActive:false},
      {x:11,    y:3,   isActive:false},
      {x:11,    y:4,   isActive:false},
      {x:11,    y:5,   isActive:false},
      {x:11,    y:6,   isActive:false},
      {x:11,    y:7,   isActive:false},
      {x:11,    y:8,   isActive:false},
      {x:11,    y:9,   isActive:false},
      {x:11,    y:10,  isActive:false},
      {x:11,    y:11,  isActive:false},
      {x:11,    y:12,  isActive:false},
      {x:11,    y:13,  isActive:false},
      {x:11,    y:14,  isActive:false},
      {x:11,    y:15,  isActive:false},
      {x:11,    y:16,  isActive:false},
      {x:11,    y:17,  isActive:true},
      {x:11,    y:18,  isActive:false},
      {x:11,    y:19,  isActive:false},
      {x:11,    y:20,  isActive:false},
  ],
  [
      {x:12,    y:1,   isActive:false},
      {x:12,    y:2,   isActive:false},
      {x:12,    y:3,   isActive:false},
      {x:12,    y:4,   isActive:false},
      {x:12,    y:5,   isActive:false},
      {x:12,    y:6,   isActive:false},
      {x:12,    y:7,   isActive:false},
      {x:12,    y:8,   isActive:false},
      {x:12,    y:9,   isActive:false},
      {x:12,    y:10,  isActive:false},
      {x:12,    y:11,  isActive:false},
      {x:12,    y:12,  isActive:false},
      {x:12,    y:13,  isActive:false},
      {x:12,    y:14,  isActive:false},
      {x:12,    y:15,  isActive:false},
      {x:12,    y:16,  isActive:false},
      {x:12,    y:17,  isActive:true},
      {x:12,    y:18,  isActive:false},
      {x:12,    y:19,  isActive:false},
      {x:12,    y:20,  isActive:false},
  ],
  [
      {x:13,    y:1,   isActive:false},
      {x:13,    y:2,   isActive:false},
      {x:13,    y:3,   isActive:false},
      {x:13,    y:4,   isActive:false},
      {x:13,    y:5,   isActive:false},
      {x:13,    y:6,   isActive:false},
      {x:13,    y:7,   isActive:false},
      {x:13,    y:8,   isActive:false},
      {x:13,    y:9,   isActive:false},
      {x:13,    y:10,  isActive:false},
      {x:13,    y:11,  isActive:false},
      {x:13,    y:12,  isActive:false},
      {x:13,    y:13,  isActive:false},
      {x:13,    y:14,  isActive:false},
      {x:13,    y:15,  isActive:false},
      {x:13,    y:16,  isActive:false},
      {x:13,    y:17,  isActive:true},
      {x:13,    y:18,  isActive:true},
      {x:13,    y:19,  isActive:true},
      {x:13,    y:20,  isActive:false},
  ],
  [
      {x:14,    y:1,   isActive:false},
      {x:14,    y:2,   isActive:false},
      {x:14,    y:3,   isActive:false},
      {x:14,    y:4,   isActive:false},
      {x:14,    y:5,   isActive:false},
      {x:14,    y:6,   isActive:false},
      {x:14,    y:7,   isActive:false},
      {x:14,    y:8,   isActive:false},
      {x:14,    y:9,   isActive:false},
      {x:14,    y:10,  isActive:false},
      {x:14,    y:11,  isActive:false},
      {x:14,    y:12,  isActive:false},
      {x:14,    y:13,  isActive:false},
      {x:14,    y:14,  isActive:false},
      {x:14,    y:15,  isActive:false},
      {x:14,    y:16,  isActive:false},
      {x:14,    y:17,  isActive:false},
      {x:14,    y:18,  isActive:false},
      {x:14,    y:19,  isActive:false},
      {x:14,    y:20,  isActive:false},
  ],
  [
      {x:15,    y:1,   isActive:false},
      {x:15,    y:2,   isActive:false},
      {x:15,    y:3,   isActive:false},
      {x:15,    y:4,   isActive:false},
      {x:15,    y:5,   isActive:false},
      {x:15,    y:6,   isActive:false},
      {x:15,    y:7,   isActive:false},
      {x:15,    y:8,   isActive:false},
      {x:15,    y:9,   isActive:false},
      {x:15,    y:10,  isActive:false},
      {x:15,    y:11,  isActive:false},
      {x:15,    y:12,  isActive:false},
      {x:15,    y:13,  isActive:false},
      {x:15,    y:14,  isActive:false},
      {x:15,    y:15,  isActive:false},
      {x:15,    y:16,  isActive:false},
      {x:15,    y:17,  isActive:false},
      {x:15,    y:18,  isActive:false},
      {x:15,    y:19,  isActive:false},
      {x:15,    y:20,  isActive:false},
  ],
];

//lab de mecânica -> T02C
const mock2 = [
  [
      {x:1,    y:1,   isActive:false},
      {x:1,    y:2,   isActive:false},
      {x:1,    y:3,   isActive:false},
      {x:1,    y:4,   isActive:false},
      {x:1,    y:5,   isActive:false},
      {x:1,    y:6,   isActive:false},
      {x:1,    y:7,   isActive:false},
      {x:1,    y:8,   isActive:false},
      {x:1,    y:9,   isActive:false},
      {x:1,    y:10,  isActive:false},
      {x:1,    y:11,  isActive:false},
      {x:1,    y:12,  isActive:false},
      {x:1,    y:13,  isActive:false},
      {x:1,    y:14,  isActive:false},
      {x:1,    y:15,  isActive:false},
      {x:1,    y:16,  isActive:false},
      {x:1,    y:17,  isActive:false},
      {x:1,    y:18,  isActive:false},
      {x:1,    y:19,  isActive:false},
      {x:1,    y:20,  isActive:false},
  ],
  [
      {x:2,    y:1,   isActive:true},
      {x:2,    y:2,   isActive:true},
      {x:2,    y:3,   isActive:false},
      {x:2,    y:4,   isActive:false},
      {x:2,    y:5,   isActive:false},
      {x:2,    y:6,   isActive:false},
      {x:2,    y:7,   isActive:false},
      {x:2,    y:8,   isActive:false},
      {x:2,    y:9,   isActive:false},
      {x:2,    y:10,  isActive:false},
      {x:2,    y:11,  isActive:false},
      {x:2,    y:12,  isActive:false},
      {x:2,    y:13,  isActive:false},
      {x:2,    y:14,  isActive:true},
      {x:2,    y:15,  isActive:false},
      {x:2,    y:16,  isActive:false},
      {x:2,    y:17,  isActive:false},
      {x:2,    y:18,  isActive:false},
      {x:2,    y:19,  isActive:false},
      {x:2,    y:20,  isActive:false},
  ],
  [
      {x:3,    y:1,   isActive:false},
      {x:3,    y:2,   isActive:true},
      {x:3,    y:3,   isActive:false},
      {x:3,    y:4,   isActive:false},
      {x:3,    y:5,   isActive:false},
      {x:3,    y:6,   isActive:false},
      {x:3,    y:7,   isActive:false},
      {x:3,    y:8,   isActive:false},
      {x:3,    y:9,   isActive:false},
      {x:3,    y:10,  isActive:false},
      {x:3,    y:11,  isActive:false},
      {x:3,    y:12,  isActive:false},
      {x:3,    y:13,  isActive:false},
      {x:3,    y:14,  isActive:false},
      {x:3,    y:15,  isActive:false},
      {x:3,    y:16,  isActive:false},
      {x:3,    y:17,  isActive:false},
      {x:3,    y:18,  isActive:false},
      {x:3,    y:19,  isActive:false},
      {x:3,    y:20,  isActive:false},
  ],
  [
      {x:4,    y:1,   isActive:false},
      {x:4,    y:2,   isActive:true},
      {x:4,    y:3,   isActive:true},
      {x:4,    y:4,   isActive:true},
      {x:4,    y:5,   isActive:true},
      {x:4,    y:6,   isActive:true},
      {x:4,    y:7,   isActive:true},
      {x:4,    y:8,   isActive:true},
      {x:4,    y:9,   isActive:true},
      {x:4,    y:10,  isActive:true},
      {x:4,    y:11,  isActive:true},
      {x:4,    y:12,  isActive:true},
      {x:4,    y:13,  isActive:true},
      {x:4,    y:14,  isActive:true},
      {x:4,    y:15,  isActive:false},
      {x:4,    y:16,  isActive:false},
      {x:4,    y:17,  isActive:false},
      {x:4,    y:18,  isActive:false},
      {x:4,    y:19,  isActive:false},
      {x:4,    y:20,  isActive:false},
  ],
  [
      {x:5,    y:1,   isActive:false},
      {x:5,    y:2,   isActive:false},
      {x:5,    y:3,   isActive:false},
      {x:5,    y:4,   isActive:false},
      {x:5,    y:5,   isActive:false},
      {x:5,    y:6,   isActive:false},
      {x:5,    y:7,   isActive:false},
      {x:5,    y:8,   isActive:false},
      {x:5,    y:9,   isActive:false},
      {x:5,    y:10,  isActive:false},
      {x:5,    y:11,  isActive:false},
      {x:5,    y:12,  isActive:false},
      {x:5,    y:13,  isActive:false},
      {x:5,    y:14,  isActive:false},
      {x:5,    y:15,  isActive:false},
      {x:5,    y:16,  isActive:false},
      {x:5,    y:17,  isActive:false},
      {x:5,    y:18,  isActive:false},
      {x:5,    y:19,  isActive:false},
      {x:5,    y:20,  isActive:false},
  ],
  [
      {x:6,    y:1,   isActive:false},
      {x:6,    y:2,   isActive:false},
      {x:6,    y:3,   isActive:false},
      {x:6,    y:4,   isActive:false},
      {x:6,    y:5,   isActive:false},
      {x:6,    y:6,   isActive:false},
      {x:6,    y:7,   isActive:false},
      {x:6,    y:8,   isActive:false},
      {x:6,    y:9,   isActive:false},
      {x:6,    y:10,  isActive:false},
      {x:6,    y:11,  isActive:false},
      {x:6,    y:12,  isActive:false},
      {x:6,    y:13,  isActive:false},
      {x:6,    y:14,  isActive:false},
      {x:6,    y:15,  isActive:false},
      {x:6,    y:16,  isActive:false},
      {x:6,    y:17,  isActive:false},
      {x:6,    y:18,  isActive:false},
      {x:6,    y:19,  isActive:false},
      {x:6,    y:20,  isActive:false},
  ],
  [
      {x:7,    y:1,   isActive:false},
      {x:7,    y:2,   isActive:false},
      {x:7,    y:3,   isActive:false},
      {x:7,    y:4,   isActive:false},
      {x:7,    y:5,   isActive:false},
      {x:7,    y:6,   isActive:false},
      {x:7,    y:7,   isActive:false},
      {x:7,    y:8,   isActive:false},
      {x:7,    y:9,   isActive:false},
      {x:7,    y:10,  isActive:false},
      {x:7,    y:11,  isActive:false},
      {x:7,    y:12,  isActive:false},
      {x:7,    y:13,  isActive:false},
      {x:7,    y:14,  isActive:false},
      {x:7,    y:15,  isActive:false},
      {x:7,    y:16,  isActive:false},
      {x:7,    y:17,  isActive:false},
      {x:7,    y:18,  isActive:false},
      {x:7,    y:19,  isActive:false},
      {x:7,    y:20,  isActive:false},
  ],
  [
      {x:8,    y:1,   isActive:false},
      {x:8,    y:2,   isActive:false},
      {x:8,    y:3,   isActive:false},
      {x:8,    y:4,   isActive:false},
      {x:8,    y:5,   isActive:false},
      {x:8,    y:6,   isActive:false},
      {x:8,    y:7,   isActive:false},
      {x:8,    y:8,   isActive:false},
      {x:8,    y:9,   isActive:false},
      {x:8,    y:10,  isActive:false},
      {x:8,    y:11,  isActive:false},
      {x:8,    y:12,  isActive:false},
      {x:8,    y:13,  isActive:false},
      {x:8,    y:14,  isActive:false},
      {x:8,    y:15,  isActive:false},
      {x:8,    y:16,  isActive:false},
      {x:8,    y:17,  isActive:false},
      {x:8,    y:18,  isActive:false},
      {x:8,    y:19,  isActive:false},
      {x:8,    y:20,  isActive:false},
  ],
  [
      {x:9,    y:1,   isActive:false},
      {x:9,    y:2,   isActive:false},
      {x:9,    y:3,   isActive:false},
      {x:9,    y:4,   isActive:false},
      {x:9,    y:5,   isActive:false},
      {x:9,    y:6,   isActive:false},
      {x:9,    y:7,   isActive:false},
      {x:9,    y:8,   isActive:false},
      {x:9,    y:9,   isActive:false},
      {x:9,    y:10,  isActive:false},
      {x:9,    y:11,  isActive:false},
      {x:9,    y:12,  isActive:false},
      {x:9,    y:13,  isActive:false},
      {x:9,    y:14,  isActive:false},
      {x:9,    y:15,  isActive:false},
      {x:9,    y:16,  isActive:false},
      {x:9,    y:17,  isActive:false},
      {x:9,    y:18,  isActive:false},
      {x:9,    y:19,  isActive:false},
      {x:9,    y:20,  isActive:false},
  ],
  [
      {x:10,    y:1,   isActive:false},
      {x:10,    y:2,   isActive:false},
      {x:10,    y:3,   isActive:false},
      {x:10,    y:4,   isActive:false},
      {x:10,    y:5,   isActive:false},
      {x:10,    y:6,   isActive:false},
      {x:10,    y:7,   isActive:false},
      {x:10,    y:8,   isActive:false},
      {x:10,    y:9,   isActive:false},
      {x:10,    y:10,  isActive:false},
      {x:10,    y:11,  isActive:false},
      {x:10,    y:12,  isActive:false},
      {x:10,    y:13,  isActive:false},
      {x:10,    y:14,  isActive:false},
      {x:10,    y:15,  isActive:false},
      {x:10,    y:16,  isActive:false},
      {x:10,    y:17,  isActive:false},
      {x:10,    y:18,  isActive:false},
      {x:10,    y:19,  isActive:false},
      {x:10,    y:20,  isActive:false},
  ],
  [
      {x:11,    y:1,   isActive:false},
      {x:11,    y:2,   isActive:false},
      {x:11,    y:3,   isActive:false},
      {x:11,    y:4,   isActive:false},
      {x:11,    y:5,   isActive:false},
      {x:11,    y:6,   isActive:false},
      {x:11,    y:7,   isActive:false},
      {x:11,    y:8,   isActive:false},
      {x:11,    y:9,   isActive:false},
      {x:11,    y:10,  isActive:false},
      {x:11,    y:11,  isActive:false},
      {x:11,    y:12,  isActive:false},
      {x:11,    y:13,  isActive:false},
      {x:11,    y:14,  isActive:false},
      {x:11,    y:15,  isActive:false},
      {x:11,    y:16,  isActive:false},
      {x:11,    y:17,  isActive:false},
      {x:11,    y:18,  isActive:false},
      {x:11,    y:19,  isActive:false},
      {x:11,    y:20,  isActive:false},
  ],
  [
      {x:12,    y:1,   isActive:false},
      {x:12,    y:2,   isActive:false},
      {x:12,    y:3,   isActive:false},
      {x:12,    y:4,   isActive:false},
      {x:12,    y:5,   isActive:false},
      {x:12,    y:6,   isActive:false},
      {x:12,    y:7,   isActive:false},
      {x:12,    y:8,   isActive:false},
      {x:12,    y:9,   isActive:false},
      {x:12,    y:10,  isActive:false},
      {x:12,    y:11,  isActive:false},
      {x:12,    y:12,  isActive:false},
      {x:12,    y:13,  isActive:false},
      {x:12,    y:14,  isActive:false},
      {x:12,    y:15,  isActive:false},
      {x:12,    y:16,  isActive:false},
      {x:12,    y:17,  isActive:false},
      {x:12,    y:18,  isActive:false},
      {x:12,    y:19,  isActive:false},
      {x:12,    y:20,  isActive:false},
  ],
  [
      {x:13,    y:1,   isActive:false},
      {x:13,    y:2,   isActive:false},
      {x:13,    y:3,   isActive:false},
      {x:13,    y:4,   isActive:false},
      {x:13,    y:5,   isActive:false},
      {x:13,    y:6,   isActive:false},
      {x:13,    y:7,   isActive:false},
      {x:13,    y:8,   isActive:false},
      {x:13,    y:9,   isActive:false},
      {x:13,    y:10,  isActive:false},
      {x:13,    y:11,  isActive:false},
      {x:13,    y:12,  isActive:false},
      {x:13,    y:13,  isActive:false},
      {x:13,    y:14,  isActive:false},
      {x:13,    y:15,  isActive:false},
      {x:13,    y:16,  isActive:false},
      {x:13,    y:17,  isActive:false},
      {x:13,    y:18,  isActive:false},
      {x:13,    y:19,  isActive:false},
      {x:13,    y:20,  isActive:false},
  ],
  [
      {x:14,    y:1,   isActive:false},
      {x:14,    y:2,   isActive:false},
      {x:14,    y:3,   isActive:false},
      {x:14,    y:4,   isActive:false},
      {x:14,    y:5,   isActive:false},
      {x:14,    y:6,   isActive:false},
      {x:14,    y:7,   isActive:false},
      {x:14,    y:8,   isActive:false},
      {x:14,    y:9,   isActive:false},
      {x:14,    y:10,  isActive:false},
      {x:14,    y:11,  isActive:false},
      {x:14,    y:12,  isActive:false},
      {x:14,    y:13,  isActive:false},
      {x:14,    y:14,  isActive:false},
      {x:14,    y:15,  isActive:false},
      {x:14,    y:16,  isActive:false},
      {x:14,    y:17,  isActive:false},
      {x:14,    y:18,  isActive:false},
      {x:14,    y:19,  isActive:false},
      {x:14,    y:20,  isActive:false},
  ],
  [
      {x:15,    y:1,   isActive:false},
      {x:15,    y:2,   isActive:false},
      {x:15,    y:3,   isActive:false},
      {x:15,    y:4,   isActive:false},
      {x:15,    y:5,   isActive:false},
      {x:15,    y:6,   isActive:false},
      {x:15,    y:7,   isActive:false},
      {x:15,    y:8,   isActive:false},
      {x:15,    y:9,   isActive:false},
      {x:15,    y:10,  isActive:false},
      {x:15,    y:11,  isActive:false},
      {x:15,    y:12,  isActive:false},
      {x:15,    y:13,  isActive:false},
      {x:15,    y:14,  isActive:false},
      {x:15,    y:15,  isActive:false},
      {x:15,    y:16,  isActive:false},
      {x:15,    y:17,  isActive:false},
      {x:15,    y:18,  isActive:false},
      {x:15,    y:19,  isActive:false},
      {x:15,    y:20,  isActive:false},
  ],
];

//T05A
const mock3 = [
  [
      {x:1,    y:1,   isActive:false},
      {x:1,    y:2,   isActive:false},
      {x:1,    y:3,   isActive:false},
      {x:1,    y:4,   isActive:false},
      {x:1,    y:5,   isActive:false},
      {x:1,    y:6,   isActive:false},
      {x:1,    y:7,   isActive:false},
      {x:1,    y:8,   isActive:false},
      {x:1,    y:9,   isActive:false},
      {x:1,    y:10,  isActive:false},
      {x:1,    y:11,  isActive:false},
      {x:1,    y:12,  isActive:false},
      {x:1,    y:13,  isActive:false},
      {x:1,    y:14,  isActive:false},
      {x:1,    y:15,  isActive:false},
      {x:1,    y:16,  isActive:false},
      {x:1,    y:17,  isActive:false},
      {x:1,    y:18,  isActive:false},
      {x:1,    y:19,  isActive:false},
      {x:1,    y:20,  isActive:false},
  ],
  [
      {x:2,    y:1,   isActive:false},
      {x:2,    y:2,   isActive:false},
      {x:2,    y:3,   isActive:false},
      {x:2,    y:4,   isActive:false},
      {x:2,    y:5,   isActive:false},
      {x:2,    y:6,   isActive:false},
      {x:2,    y:7,   isActive:false},
      {x:2,    y:8,   isActive:false},
      {x:2,    y:9,   isActive:false},
      {x:2,    y:10,  isActive:false},
      {x:2,    y:11,  isActive:false},
      {x:2,    y:12,  isActive:false},
      {x:2,    y:13,  isActive:false},
      {x:2,    y:14,  isActive:false},
      {x:2,    y:15,  isActive:false},
      {x:2,    y:16,  isActive:false},
      {x:2,    y:17,  isActive:false},
      {x:2,    y:18,  isActive:false},
      {x:2,    y:19,  isActive:false},
      {x:2,    y:20,  isActive:false},
  ],
  [
      {x:3,    y:1,   isActive:false},
      {x:3,    y:2,   isActive:false},
      {x:3,    y:3,   isActive:false},
      {x:3,    y:4,   isActive:false},
      {x:3,    y:5,   isActive:false},
      {x:3,    y:6,   isActive:false},
      {x:3,    y:7,   isActive:true},
      {x:3,    y:8,   isActive:false},
      {x:3,    y:9,   isActive:false},
      {x:3,    y:10,  isActive:false},
      {x:3,    y:11,  isActive:false},
      {x:3,    y:12,  isActive:false},
      {x:3,    y:13,  isActive:false},
      {x:3,    y:14,  isActive:false},
      {x:3,    y:15,  isActive:false},
      {x:3,    y:16,  isActive:false},
      {x:3,    y:17,  isActive:false},
      {x:3,    y:18,  isActive:false},
      {x:3,    y:19,  isActive:false},
      {x:3,    y:20,  isActive:false},
  ],
  [
      {x:4,    y:1,   isActive:false},
      {x:4,    y:2,   isActive:false},
      {x:4,    y:3,   isActive:false},
      {x:4,    y:4,   isActive:false},
      {x:4,    y:5,   isActive:false},
      {x:4,    y:6,   isActive:false},
      {x:4,    y:7,   isActive:false},
      {x:4,    y:8,   isActive:false},
      {x:4,    y:9,   isActive:false},
      {x:4,    y:10,  isActive:false},
      {x:4,    y:11,  isActive:false},
      {x:4,    y:12,  isActive:false},
      {x:4,    y:13,  isActive:false},
      {x:4,    y:14,  isActive:false},
      {x:4,    y:15,  isActive:false},
      {x:4,    y:16,  isActive:false},
      {x:4,    y:17,  isActive:false},
      {x:4,    y:18,  isActive:false},
      {x:4,    y:19,  isActive:false},
      {x:4,    y:20,  isActive:false},
  ],
  [
      {x:5,    y:1,   isActive:false},
      {x:5,    y:2,   isActive:false},
      {x:5,    y:3,   isActive:false},
      {x:5,    y:4,   isActive:false},
      {x:5,    y:5,   isActive:false},
      {x:5,    y:6,   isActive:false},
      {x:5,    y:7,   isActive:false},
      {x:5,    y:8,   isActive:false},
      {x:5,    y:9,   isActive:false},
      {x:5,    y:10,  isActive:false},
      {x:5,    y:11,  isActive:false},
      {x:5,    y:12,  isActive:false},
      {x:5,    y:13,  isActive:false},
      {x:5,    y:14,  isActive:false},
      {x:5,    y:15,  isActive:false},
      {x:5,    y:16,  isActive:false},
      {x:5,    y:17,  isActive:false},
      {x:5,    y:18,  isActive:false},
      {x:5,    y:19,  isActive:false},
      {x:5,    y:20,  isActive:false},
  ],
  [
      {x:6,    y:1,   isActive:false},
      {x:6,    y:2,   isActive:false},
      {x:6,    y:3,   isActive:false},
      {x:6,    y:4,   isActive:false},
      {x:6,    y:5,   isActive:false},
      {x:6,    y:6,   isActive:false},
      {x:6,    y:7,   isActive:false},
      {x:6,    y:8,   isActive:false},
      {x:6,    y:9,   isActive:false},
      {x:6,    y:10,  isActive:false},
      {x:6,    y:11,  isActive:false},
      {x:6,    y:12,  isActive:false},
      {x:6,    y:13,  isActive:false},
      {x:6,    y:14,  isActive:false},
      {x:6,    y:15,  isActive:false},
      {x:6,    y:16,  isActive:false},
      {x:6,    y:17,  isActive:false},
      {x:6,    y:18,  isActive:false},
      {x:6,    y:19,  isActive:false},
      {x:6,    y:20,  isActive:false},
  ],
  [
      {x:7,    y:1,   isActive:false},
      {x:7,    y:2,   isActive:false},
      {x:7,    y:3,   isActive:false},
      {x:7,    y:4,   isActive:false},
      {x:7,    y:5,   isActive:false},
      {x:7,    y:6,   isActive:false},
      {x:7,    y:7,   isActive:false},
      {x:7,    y:8,   isActive:false},
      {x:7,    y:9,   isActive:false},
      {x:7,    y:10,  isActive:false},
      {x:7,    y:11,  isActive:false},
      {x:7,    y:12,  isActive:false},
      {x:7,    y:13,  isActive:false},
      {x:7,    y:14,  isActive:false},
      {x:7,    y:15,  isActive:false},
      {x:7,    y:16,  isActive:false},
      {x:7,    y:17,  isActive:false},
      {x:7,    y:18,  isActive:false},
      {x:7,    y:19,  isActive:false},
      {x:7,    y:20,  isActive:false},
  ],
  [
      {x:8,    y:1,   isActive:false},
      {x:8,    y:2,   isActive:false},
      {x:8,    y:3,   isActive:false},
      {x:8,    y:4,   isActive:false},
      {x:8,    y:5,   isActive:false},
      {x:8,    y:6,   isActive:false},
      {x:8,    y:7,   isActive:false},
      {x:8,    y:8,   isActive:false},
      {x:8,    y:9,   isActive:false},
      {x:8,    y:10,  isActive:false},
      {x:8,    y:11,  isActive:false},
      {x:8,    y:12,  isActive:false},
      {x:8,    y:13,  isActive:false},
      {x:8,    y:14,  isActive:false},
      {x:8,    y:15,  isActive:false},
      {x:8,    y:16,  isActive:false},
      {x:8,    y:17,  isActive:false},
      {x:8,    y:18,  isActive:false},
      {x:8,    y:19,  isActive:false},
      {x:8,    y:20,  isActive:false},
  ],
  [
      {x:9,    y:1,   isActive:false},
      {x:9,    y:2,   isActive:false},
      {x:9,    y:3,   isActive:false},
      {x:9,    y:4,   isActive:false},
      {x:9,    y:5,   isActive:false},
      {x:9,    y:6,   isActive:false},
      {x:9,    y:7,   isActive:false},
      {x:9,    y:8,   isActive:false},
      {x:9,    y:9,   isActive:false},
      {x:9,    y:10,  isActive:false},
      {x:9,    y:11,  isActive:false},
      {x:9,    y:12,  isActive:false},
      {x:9,    y:13,  isActive:false},
      {x:9,    y:14,  isActive:false},
      {x:9,    y:15,  isActive:false},
      {x:9,    y:16,  isActive:false},
      {x:9,    y:17,  isActive:false},
      {x:9,    y:18,  isActive:false},
      {x:9,    y:19,  isActive:false},
      {x:9,    y:20,  isActive:false},
  ],
  [
      {x:10,    y:1,   isActive:false},
      {x:10,    y:2,   isActive:false},
      {x:10,    y:3,   isActive:false},
      {x:10,    y:4,   isActive:false},
      {x:10,    y:5,   isActive:false},
      {x:10,    y:6,   isActive:false},
      {x:10,    y:7,   isActive:false},
      {x:10,    y:8,   isActive:false},
      {x:10,    y:9,   isActive:false},
      {x:10,    y:10,  isActive:false},
      {x:10,    y:11,  isActive:false},
      {x:10,    y:12,  isActive:false},
      {x:10,    y:13,  isActive:false},
      {x:10,    y:14,  isActive:false},
      {x:10,    y:15,  isActive:false},
      {x:10,    y:16,  isActive:false},
      {x:10,    y:17,  isActive:false},
      {x:10,    y:18,  isActive:false},
      {x:10,    y:19,  isActive:false},
      {x:10,    y:20,  isActive:false},
  ],
  [
      {x:11,    y:1,   isActive:false},
      {x:11,    y:2,   isActive:false},
      {x:11,    y:3,   isActive:false},
      {x:11,    y:4,   isActive:false},
      {x:11,    y:5,   isActive:false},
      {x:11,    y:6,   isActive:false},
      {x:11,    y:7,   isActive:false},
      {x:11,    y:8,   isActive:false},
      {x:11,    y:9,   isActive:false},
      {x:11,    y:10,  isActive:false},
      {x:11,    y:11,  isActive:false},
      {x:11,    y:12,  isActive:false},
      {x:11,    y:13,  isActive:false},
      {x:11,    y:14,  isActive:false},
      {x:11,    y:15,  isActive:false},
      {x:11,    y:16,  isActive:false},
      {x:11,    y:17,  isActive:false},
      {x:11,    y:18,  isActive:false},
      {x:11,    y:19,  isActive:false},
      {x:11,    y:20,  isActive:false},
  ],
  [
      {x:12,    y:1,   isActive:false},
      {x:12,    y:2,   isActive:false},
      {x:12,    y:3,   isActive:false},
      {x:12,    y:4,   isActive:false},
      {x:12,    y:5,   isActive:false},
      {x:12,    y:6,   isActive:false},
      {x:12,    y:7,   isActive:false},
      {x:12,    y:8,   isActive:false},
      {x:12,    y:9,   isActive:false},
      {x:12,    y:10,  isActive:false},
      {x:12,    y:11,  isActive:false},
      {x:12,    y:12,  isActive:false},
      {x:12,    y:13,  isActive:false},
      {x:12,    y:14,  isActive:false},
      {x:12,    y:15,  isActive:false},
      {x:12,    y:16,  isActive:false},
      {x:12,    y:17,  isActive:false},
      {x:12,    y:18,  isActive:false},
      {x:12,    y:19,  isActive:false},
      {x:12,    y:20,  isActive:false},
  ],
  [
      {x:13,    y:1,   isActive:false},
      {x:13,    y:2,   isActive:false},
      {x:13,    y:3,   isActive:false},
      {x:13,    y:4,   isActive:false},
      {x:13,    y:5,   isActive:false},
      {x:13,    y:6,   isActive:false},
      {x:13,    y:7,   isActive:false},
      {x:13,    y:8,   isActive:false},
      {x:13,    y:9,   isActive:false},
      {x:13,    y:10,  isActive:false},
      {x:13,    y:11,  isActive:false},
      {x:13,    y:12,  isActive:false},
      {x:13,    y:13,  isActive:false},
      {x:13,    y:14,  isActive:false},
      {x:13,    y:15,  isActive:false},
      {x:13,    y:16,  isActive:false},
      {x:13,    y:17,  isActive:false},
      {x:13,    y:18,  isActive:false},
      {x:13,    y:19,  isActive:false},
      {x:13,    y:20,  isActive:false},
  ],
  [
      {x:14,    y:1,   isActive:false},
      {x:14,    y:2,   isActive:false},
      {x:14,    y:3,   isActive:false},
      {x:14,    y:4,   isActive:false},
      {x:14,    y:5,   isActive:false},
      {x:14,    y:6,   isActive:false},
      {x:14,    y:7,   isActive:false},
      {x:14,    y:8,   isActive:false},
      {x:14,    y:9,   isActive:false},
      {x:14,    y:10,  isActive:false},
      {x:14,    y:11,  isActive:false},
      {x:14,    y:12,  isActive:false},
      {x:14,    y:13,  isActive:false},
      {x:14,    y:14,  isActive:false},
      {x:14,    y:15,  isActive:false},
      {x:14,    y:16,  isActive:false},
      {x:14,    y:17,  isActive:false},
      {x:14,    y:18,  isActive:false},
      {x:14,    y:19,  isActive:false},
      {x:14,    y:20,  isActive:false},
  ],
  [
      {x:15,    y:1,   isActive:false},
      {x:15,    y:2,   isActive:false},
      {x:15,    y:3,   isActive:false},
      {x:15,    y:4,   isActive:false},
      {x:15,    y:5,   isActive:false},
      {x:15,    y:6,   isActive:false},
      {x:15,    y:7,   isActive:false},
      {x:15,    y:8,   isActive:false},
      {x:15,    y:9,   isActive:false},
      {x:15,    y:10,  isActive:false},
      {x:15,    y:11,  isActive:false},
      {x:15,    y:12,  isActive:false},
      {x:15,    y:13,  isActive:false},
      {x:15,    y:14,  isActive:false},
      {x:15,    y:15,  isActive:false},
      {x:15,    y:16,  isActive:false},
      {x:15,    y:17,  isActive:false},
      {x:15,    y:18,  isActive:false},
      {x:15,    y:19,  isActive:false},
      {x:15,    y:20,  isActive:false},
  ],
];

// const mock1 = [[
//   {x:1, y:1, isActive:true},
//   {x:1, y:2, isActive:true},
//   {x:1, y:3, isActive:true},
//   {x:1, y:4, isActive:false},
//   {x:1, y:5, isActive:false},
//   {x:1, y:6, isActive:false},
//   {x:1, y:7, isActive:false},
//   {x:1, y:8, isActive:false},
//   {x:1, y:9, isActive:false},
//   {x:1, y:10, isActive:false},
//   {x:1, y:11, isActive:false},
//   {x:1, y:12, isActive:false},
//   {x:1, y:13, isActive:false},
//   {x:1, y:14, isActive:false},
//   {x:1, y:15, isActive:false},
//   {x:1, y:16, isActive:false},
//   {x:1, y:17, isActive:false},
//   {x:1, y:18, isActive:false},
//   {x:1, y:19, isActive:false},
//   {x:1, y:20, isActive:false},
// ],
// [
//   {x:2, y:1, isActive:false},
//   {x:2, y:2, isActive:false},
//   {x:2, y:3, isActive:true},
//   {x:2, y:4, isActive:true},
//   {x:2, y:5, isActive:true},
//   {x:2, y:6, isActive:true},
//   {x:2, y:7, isActive:false},
//   {x:2, y:8, isActive:false},
//   {x:2, y:9, isActive:false},
//   {x:2, y:10, isActive:false},
//   {x:2, y:11, isActive:false},
//   {x:2, y:12, isActive:false},
//   {x:2, y:13, isActive:false},
//   {x:2, y:14, isActive:false},
//   {x:2, y:15, isActive:false},
//   {x:2, y:16, isActive:false},
//   {x:2, y:17, isActive:false},
//   {x:2, y:18, isActive:false},
//   {x:2, y:19, isActive:false},
//   {x:2, y:20, isActive:false},
// ],
// [
//   {x:3, y:1, isActive:false},
//   {x:3, y:2, isActive:false},
//   {x:3, y:3, isActive:false},
//   {x:3, y:4, isActive:false},
//   {x:3, y:5, isActive:false},
//   {x:3, y:6, isActive:true},
//   {x:3, y:7, isActive:false},
//   {x:3, y:8, isActive:false},
//   {x:3, y:9, isActive:false},
//   {x:3, y:10, isActive:false},
//   {x:3, y:11, isActive:false},
//   {x:3, y:12, isActive:false},
//   {x:3, y:13, isActive:false},
//   {x:3, y:14, isActive:false},
//   {x:3, y:15, isActive:false},
//   {x:3, y:16, isActive:false},
//   {x:3, y:17, isActive:false},
//   {x:3, y:18, isActive:false},
//   {x:3, y:19, isActive:false},
//   {x:3, y:20, isActive:false},
// ],
// [
//   {x:4, y:1, isActive:false},
//   {x:4, y:2, isActive:false},
//   {x:4, y:3, isActive:false},
//   {x:4, y:4, isActive:false},
//   {x:4, y:5, isActive:false},
//   {x:4, y:6, isActive:true},
//   {x:4, y:7, isActive:false},
//   {x:4, y:8, isActive:false},
//   {x:4, y:9, isActive:false},
//   {x:4, y:10, isActive:false},
//   {x:4, y:11, isActive:false},
//   {x:4, y:12, isActive:false},
//   {x:4, y:13, isActive:false},
//   {x:4, y:14, isActive:false},
//   {x:4, y:15, isActive:false},
//   {x:4, y:16, isActive:false},
//   {x:4, y:17, isActive:false},
//   {x:4, y:18, isActive:false},
//   {x:4, y:19, isActive:false},
//   {x:4, y:20, isActive:false},
// ],
// [
//   {x:5, y:1, isActive:false},
//   {x:5, y:2, isActive:false},
//   {x:5, y:3, isActive:false},
//   {x:5, y:4, isActive:false},
//   {x:5, y:5, isActive:false},
//   {x:5, y:6, isActive:true},
//   {x:5, y:7, isActive:false},
//   {x:5, y:8, isActive:false},
//   {x:5, y:9, isActive:false},
//   {x:5, y:10, isActive:false},
//   {x:5, y:11, isActive:false},
//   {x:5, y:12, isActive:false},
//   {x:5, y:13, isActive:false},
//   {x:5, y:14, isActive:false},
//   {x:5, y:15, isActive:false},
//   {x:5, y:16, isActive:false},
//   {x:5, y:17, isActive:false},
//   {x:5, y:18, isActive:false},
//   {x:5, y:19, isActive:false},
//   {x:5, y:20, isActive:false},
// ],
// [
//   {x:6, y:1, isActive:false},
//   {x:6, y:2, isActive:false},
//   {x:6, y:3, isActive:false},
//   {x:6, y:4, isActive:false},
//   {x:6, y:5, isActive:false},
//   {x:6, y:6, isActive:true},
//   {x:6, y:7, isActive:false},
//   {x:6, y:8, isActive:false},
//   {x:6, y:9, isActive:false},
//   {x:6, y:10, isActive:false},
//   {x:6, y:11, isActive:false},
//   {x:6, y:12, isActive:false},
//   {x:6, y:13, isActive:false},
//   {x:6, y:14, isActive:false},
//   {x:6, y:15, isActive:false},
//   {x:6, y:16, isActive:false},
//   {x:6, y:17, isActive:false},
//   {x:6, y:18, isActive:false},
//   {x:6, y:19, isActive:false},
//   {x:6, y:20, isActive:false},
// ],
// ];